name: "Test Report"
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@df6247429542221bc30d46a036ee47af1102c451 # v2.7.0
        with:
          artifact: test-results
          name: JEST Tests
          path: "*.xml"
          reporter: jest-junit
